export const MARGIN_MODULE_ABI = [
  {
    inputs: [
      { internalType: "address", name: "_factory", type: "address" },
      { internalType: "address", name: "_router", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "positionId", type: "uint256" },
      { indexed: false, internalType: "address", name: "assetIn", type: "address" },
      { indexed: false, internalType: "address", name: "assetOut", type: "address" },
      { indexed: false, internalType: "uint256", name: "amountIn", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "amountOut", type: "uint256" },
    ],
    name: "MarginSwap",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "orderId", type: "uint256" },
      { indexed: true, internalType: "address", name: "owner", type: "address" },
      { indexed: true, internalType: "address", name: "baseAsset", type: "address" },
      { indexed: false, internalType: "uint256", name: "interestRate", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "duration", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "minLoan", type: "uint256" },
      { indexed: false, internalType: "uint8", name: "leverage", type: "uint8" },
    ],
    name: "OrderCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "orderId", type: "uint256" },
      { indexed: true, internalType: "address", name: "asset", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "OrderDeposit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "orderId", type: "uint256" },
      { indexed: true, internalType: "address", name: "asset", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "OrderWithdraw",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "positionId", type: "uint256" },
      { indexed: true, internalType: "address", name: "asset", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "PositionDeposit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "positionId", type: "uint256" },
      { indexed: true, internalType: "address", name: "liquidator", type: "address" },
      { indexed: false, internalType: "uint256", name: "timestamp", type: "uint256" },
    ],
    name: "PositionFrozen",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "positionId", type: "uint256" },
      { indexed: true, internalType: "address", name: "liquidator", type: "address" },
      { indexed: false, internalType: "uint256", name: "rewardAmount", type: "uint256" },
    ],
    name: "PositionLiquidated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "positionId", type: "uint256" },
      { indexed: true, internalType: "address", name: "owner", type: "address" },
      { indexed: false, internalType: "uint256", name: "loanAmount", type: "uint256" },
      { indexed: false, internalType: "address", name: "baseAsset", type: "address" },
    ],
    name: "PositionOpened",
    type: "event",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_orderId", type: "uint256" },
      { internalType: "address[]", name: "collateral", type: "address[]" },
    ],
    name: "activateOrder",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address[]", name: "tokens", type: "address[]" },
      { internalType: "bool", name: "isContract", type: "bool" },
    ],
    name: "addTokenlist",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "bytes32", name: "whitelistId", type: "bytes32" },
          { internalType: "uint256", name: "interestRate", type: "uint256" },
          { internalType: "uint256", name: "duration", type: "uint256" },
          { internalType: "uint256", name: "minLoan", type: "uint256" },
          { internalType: "uint256", name: "liquidationRewardAmount", type: "uint256" },
          { internalType: "address", name: "liquidationRewardAsset", type: "address" },
          { internalType: "address", name: "asset", type: "address" },
          { internalType: "uint32", name: "deadline", type: "uint32" },
          { internalType: "uint16", name: "currencyLimit", type: "uint16" },
          { internalType: "uint8", name: "leverage", type: "uint8" },
          { internalType: "address", name: "oracle", type: "address" },
          { internalType: "address[]", name: "collateral", type: "address[]" },
        ],
        internalType: "struct MarginModule.OrderParams",
        name: "params",
        type: "tuple",
      },
    ],
    name: "createOrder",
    outputs: [{ internalType: "bool", name: "success", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "address", name: "", type: "address" },
    ],
    name: "erc223deposit",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "factory",
    outputs: [{ internalType: "contract IDex223Factory", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "positionId", type: "uint256" },
      { internalType: "address", name: "asset", type: "address" },
    ],
    name: "getAssetId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "_listId", type: "bytes32" },
      { internalType: "address", name: "asset", type: "address" },
    ],
    name: "getIdFromTokenlist",
    outputs: [{ internalType: "uint256", name: "assetId", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    name: "getOrderCollateralAssets",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    name: "getOrderExpirationData",
    outputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint32", name: "", type: "uint32" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getOrdersLength",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    name: "getPositionAssets",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    name: "getPositionBalances",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPositionsLength",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "id", type: "uint256" }],
    name: "isOrderOpen",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "positionId", type: "uint256" }],
    name: "liquidate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_positionId", type: "uint256" },
      { internalType: "uint256", name: "_assetId1", type: "uint256" },
      { internalType: "uint256", name: "_whitelistId1", type: "uint256" },
      { internalType: "uint256", name: "_whitelistId2", type: "uint256" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
      { internalType: "address", name: "_asset2", type: "address" },
      { internalType: "uint24", name: "_feeTier", type: "uint24" },
    ],
    name: "marginSwap",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_positionId", type: "uint256" },
      { internalType: "uint256", name: "_assetId1", type: "uint256" },
      { internalType: "uint256", name: "_whitelistId1", type: "uint256" },
      { internalType: "uint256", name: "_whitelistId2", type: "uint256" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
      { internalType: "address", name: "_asset2", type: "address" },
      { internalType: "uint24", name: "_feeTier", type: "uint24" },
    ],
    name: "marginSwap223",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_orderId", type: "uint256" },
      { internalType: "bytes32", name: "_whitelist", type: "bytes32" },
      { internalType: "uint256", name: "_interestRate", type: "uint256" },
      { internalType: "uint256", name: "_duration", type: "uint256" },
      { internalType: "uint256", name: "_minLoan", type: "uint256" },
      { internalType: "uint16", name: "_currencyLimit", type: "uint16" },
      { internalType: "uint8", name: "_leverage", type: "uint8" },
      { internalType: "address", name: "_oracle", type: "address" },
      { internalType: "uint256", name: "_liquidationRewardAmount", type: "uint256" },
      { internalType: "address", name: "_liquidationRewardAsset", type: "address" },
      { internalType: "uint32", name: "_deadline", type: "uint32" },
    ],
    name: "modifyOrder",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes[]", name: "data", type: "bytes[]" }],
    name: "multicall",
    outputs: [{ internalType: "bytes[]", name: "results", type: "bytes[]" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_orderId", type: "uint256" }],
    name: "orderDepositEth",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_orderId", type: "uint256" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "orderDepositToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_orderId", type: "uint256" },
      { internalType: "address", name: "_WETH9", type: "address" },
    ],
    name: "orderDepositWETH9",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_orderId", type: "uint256" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "orderWithdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "order_status",
    outputs: [
      { internalType: "bool", name: "alive", type: "bool" },
      { internalType: "uint8", name: "positions", type: "uint8" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "orders",
    outputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "bytes32", name: "whitelist", type: "bytes32" },
      { internalType: "uint256", name: "interestRate", type: "uint256" },
      { internalType: "uint256", name: "duration", type: "uint256" },
      { internalType: "uint256", name: "minLoan", type: "uint256" },
      { internalType: "address", name: "baseAsset", type: "address" },
      { internalType: "uint16", name: "currencyLimit", type: "uint16" },
      { internalType: "uint8", name: "leverage", type: "uint8" },
      { internalType: "address", name: "oracle", type: "address" },
      { internalType: "uint256", name: "balance", type: "uint256" },
      {
        components: [
          { internalType: "uint256", name: "liquidationRewardAmount", type: "uint256" },
          { internalType: "address", name: "liquidationRewardAsset", type: "address" },
          { internalType: "uint32", name: "deadline", type: "uint32" },
        ],
        internalType: "struct MarginModule.OrderExpiration",
        name: "expirationData",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "positionId", type: "uint256" }],
    name: "positionClose",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "positionId", type: "uint256" },
      { internalType: "address", name: "asset", type: "address" },
      { internalType: "uint256", name: "idInWhitelist", type: "uint256" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "positionDeposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "positionId", type: "uint256" },
      { internalType: "address", name: "asset", type: "address" },
    ],
    name: "positionWithdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "positions",
    outputs: [
      { internalType: "uint256", name: "orderId", type: "uint256" },
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
      { internalType: "uint256", name: "createdAt", type: "uint256" },
      { internalType: "uint256", name: "initialBalance", type: "uint256" },
      { internalType: "uint256", name: "interest", type: "uint256" },
      { internalType: "uint256", name: "paidDays", type: "uint256" },
      { internalType: "bool", name: "open", type: "bool" },
      { internalType: "uint256", name: "frozenTime", type: "uint256" },
      { internalType: "address", name: "liquidator", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address[]", name: "tokens", type: "address[]" },
      { internalType: "bool", name: "isContract", type: "bool" },
    ],
    name: "predictTokenListsID",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "router",
    outputs: [{ internalType: "contract ISwapRouter", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_orderId", type: "uint256" },
      { internalType: "bool", name: "_status", type: "bool" },
    ],
    name: "setOrderStatus",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "positionId", type: "uint256" }],
    name: "subjectToLiquidation",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_orderId", type: "uint256" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
      { internalType: "uint256", name: "_collateralIdx", type: "uint256" },
      { internalType: "uint256", name: "_collateralAmount", type: "uint256" },
    ],
    name: "takeLoan",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint256", name: "value", type: "uint256" },
      { internalType: "bytes", name: "data", type: "bytes" },
    ],
    name: "tokenReceived",
    outputs: [{ internalType: "bytes4", name: "", type: "bytes4" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "tokenlists",
    outputs: [
      { internalType: "bool", name: "exists", type: "bool" },
      { internalType: "bool", name: "isContract", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "asset", type: "address" }],
    name: "withdraw223",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
